version: '3'
  
services:

  server:
    image: nginx:stable-alpine
    container_name: server
    restart: unless-stopped
    tty: true
    # exposing its :80 port as :8080 on our local machine
    ports:
      - 80:80
    
    # - ./api folder is bound to the container’s /var/www path. anything we modify in /api 
    # will be available to the server under /var/www immediately.
    # - ./server/default.conf file we created is linked to the /etc/nginx/conf.d/default.conf container file, 
    # and will give us the ability to modify the web server on our local machine.

    volumes:
      - ./api:/var/www
      - ./api/docker-files/server/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./api:/var/www
    working_dir: /var/www
    networks:
      - net

  database:
    image: mariadb:10.5.6
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pldb
      MYSQL_ROOT_PASSWORD: ./dbpwd.txt
    volumes:
      - storage:/var/lib/mysql
      - ./api/docker-files/database/my.cnf:/etc/mysql/my.cnf
    networks:
      - net

networks:
  net:
    driver: bridge

secrets:
  dbpwd:
    file: ./dbpwd.txt
  
volumes:
  storage:
    driver: local